language: java
sudo: false
services:
  - docker

script: "mvn test"

after_success:
  #- docker build -t ravindra88/product-service -f ./product-service/Dockerfile ./product-service
  - docker build -t ravindra88/order-service -f ./order-service/Dockerfile ./order-service
  #- docker build -t ravindra88/api-gateway -f ./api-gateway/Dockerfile ./api-gateway
  #- docker build -t ravindra88/discovery-server -f ./discovery-server/Dockerfile ./discovery-server
  # Log in to the docker CLI to
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Take those images and push them to docker hub
  #- docker push ravindra88/product-service
  - docker push ravindra88/order-service
  #- docker push ravindra88/api-gateway
  #- docker push ravindra88/discovery-server
deploy:
  skip_cleanup: true
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "docker-micro-services"
  env: "Dockermicroservices-env"
  bucket_name: "elasticbeanstalk-us-east-2-381128197141"
  bucket_path: "docker-micro-service"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECURE_KEY
