version: '3.8'
services:
  order-service:
    container_name: order-service
    image: ravindra88/order-service
    ports:
      - "8283:8283"
    depends_on:
      - discovery-server 
    networks:
      - spring-cloud-network   
networks:
  spring-cloud-network:
    driver: bridge     
